services:
  - type: web
    name: eduseen-be
    runtime: dotnet
    branch: main

    buildCommand: dotnet publish -c Release -o out
    startCommand: dotnet out/Sep490_Eduseen_BE.dll

    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__Default
        sync: false