// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sep490_Eduseen_BE.Models;

#nullable disable

namespace Sep490_Eduseen_BE.Migrations
{
    [DbContext(typeof(Sep490EduseenContext))]
    partial class Sep490EduseenContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sep490_Eduseen_BE.Models.Assignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("assignment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("course_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("due_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.HasKey("AssignmentId")
                        .HasName("PK__Assignme__DA891814505DEDAD");

                    b.HasIndex("CourseId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("Sep490_Eduseen_BE.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("category_name");

                    b.HasKey("CategoryId")
                        .HasName("PK__Categori__D54EE9B4C08CD780");

                    b.HasIndex(new[] { "CategoryName" }, "UQ__Categori__5189E2557A4064D3")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Sep490_Eduseen_BE.Models.ChatMessage", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("message_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("course_id");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message_text");

                    b.Property<int>("SenderId")
                        .HasColumnType("int")
                        .HasColumnName("sender_id");

                    b.Property<DateTime?>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("sent_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("MessageId")
                        .HasName("PK__ChatMess__0BBF6EE6E3BD7CD9");

                    b.HasIndex("CourseId");

                    b.HasIndex("SenderId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("Sep490_Eduseen_BE.Models.Class", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassId"));

                    b.Property<string>("ClassCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("class_code");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("class_name");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int")
                        .HasColumnName("teacher_id");

                    b.HasKey("ClassId")
                        .HasName("PK__Classes__FDF47986B4015B69");

                    b.HasIndex("TeacherId");

                    b.HasIndex(new[] { "ClassCode" }, "UQ__Classes__0AF9B2E4AE4DCCFE")
                        .IsUnique();

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("Sep490_Eduseen_BE.Models.ClassCourse", b =>
                {
                    b.Property<int>("ClassCourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("class_course_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassCourseId"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("course_id");

                    b.HasKey("ClassCourseId")
                        .HasName("PK__ClassCou__869DCFE1C6D40342");

                    b.HasIndex("CourseId");

                    b.HasIndex(new[] { "ClassId", "CourseId" }, "UC_ClassCourses")
                        .IsUnique();

                    b.ToTable("ClassCourses");
                });

            modelBuilder.Entity("Sep490_Eduseen_BE.Models.ClassStudent", b =>
                {
                    b.Property<int>("ClassStudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("class_student_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassStudentId"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    b.Property<DateTime?>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("joined_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.HasKey("ClassStudentId")
                        .HasName("PK__ClassStu__86B74A0BD1B1B359");

                    b.HasIndex("StudentId");

                    b.HasIndex(new[] { "ClassId", "StudentId" }, "UC_ClassStudents")
                        .IsUnique();

                    b.ToTable("ClassStudents");
                });

            modelBuilder.Entity("Sep490_Eduseen_BE.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("course_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Level")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("level");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int")
                        .HasColumnName("teacher_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("CourseId")
                        .HasName("PK__Courses__8F1EF7AE66FFCB25");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Sep490_Eduseen_BE.Models.EmailConfirmationToken", b =>
                {
                    b.Property<int>("EmailConfirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("email_confirm_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmailConfirmId"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("expires_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("token");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("EmailConfirmId");

                    b.HasIndex("UserId");

                    b.ToTable("EmailConfirmationToken", (string)null);
                });

            modelBuilder.Entity("Sep490_Eduseen_BE.Models.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("enrollment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("course_id");

                    b.Property<DateTime?>("EnrolledAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("enrolled_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.HasKey("EnrollmentId")
                        .HasName("PK__Enrollme__6D24AA7ABE2E1AC6");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("Sep490_Eduseen_BE.Models.Favorite", b =>
                {
                    b.Property<int>("FavoriteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("favorite_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FavoriteId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("course_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.HasKey("FavoriteId")
                        .HasName("PK__Favorite__46ACF4CBBA912BBF");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("Sep490_Eduseen_BE.Models.Lecture", b =>
                {
                    b.Property<int>("LectureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("lecture_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LectureId"));

                    b.Property<string>("ContentType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("content_type");

                    b.Property<string>("ContentUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("content_url");

                    b.Property<int?>("Duration")
                        .HasColumnType("int")
                        .HasColumnName("duration");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("order");

                    b.Property<int>("SectionId")
                        .HasColumnType("int")
                        .HasColumnName("section_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.HasKey("LectureId")
                        .HasName("PK__Lectures__797827F5DABC7A39");

                    b.HasIndex("SectionId");

                    b.ToTable("Lectures");
                });

            modelBuilder.Entity("Sep490_Eduseen_BE.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("notification_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__E059842F56D909F9");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Sep490_Eduseen_BE.Models.Otp", b =>
                {
                    b.Property<int>("OtpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("otp_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OtpId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("")
                        .HasColumnName("email");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("expires_at");

                    b.Property<bool?>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_used");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasDefaultValue("")
                        .HasColumnName("otp_code");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("OtpId")
                        .HasName("PK__Otps__AEE354356962EF9E");

                    b.HasIndex("UserId");

                    b.ToTable("Otps");
                });

            modelBuilder.Entity("Sep490_Eduseen_BE.Models.PasswordResetToken", b =>
                {
                    b.Property<int>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("token_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TokenId"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("expires_at");

                    b.Property<string>("Token")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("token");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("TokenId")
                        .HasName("PK__Password__CB3C9E1762132C3D");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("Sep490_Eduseen_BE.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("review_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comment");

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("course_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.HasKey("ReviewId")
                        .HasName("PK__Reviews__60883D905BD52DFC");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Sep490_Eduseen_BE.Models.ReviewResponse", b =>
                {
                    b.Property<int>("ResponseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("response_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResponseId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ResponseText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("response_text");

                    b.Property<int>("ReviewId")
                        .HasColumnType("int")
                        .HasColumnName("review_id");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int")
                        .HasColumnName("teacher_id");

                    b.HasKey("ResponseId")
                        .HasName("PK__ReviewRe__EBECD89688310922");

                    b.HasIndex("ReviewId");

                    b.HasIndex("TeacherId");

                    b.ToTable("ReviewResponses");
                });

            modelBuilder.Entity("Sep490_Eduseen_BE.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__760965CC83467F9F");

                    b.HasIndex(new[] { "RoleName" }, "UQ__Roles__783254B1196FC9B2")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Sep490_Eduseen_BE.Models.Schedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("schedule_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<int>("Duration")
                        .HasColumnType("int")
                        .HasColumnName("duration");

                    b.Property<DateTime>("ScheduledTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("scheduled_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int")
                        .HasColumnName("teacher_id");

                    b.HasKey("ScheduleId")
                        .HasName("PK__Schedule__C46A8A6FD5BDFD86");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("Sep490_Eduseen_BE.Models.Section", b =>
                {
                    b.Property<int>("SectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("section_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SectionId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("course_id");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.HasKey("SectionId")
                        .HasName("PK__Sections__F842676A60047FF6");

                    b.HasIndex("CourseId");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("Sep490_Eduseen_BE.Models.Submission", b =>
                {
                    b.Property<int>("SubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("submission_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubmissionId"));

                    b.Property<int>("AssignmentId")
                        .HasColumnType("int")
                        .HasColumnName("assignment_id");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int")
                        .HasColumnName("attempt_number");

                    b.Property<string>("Feedback")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("feedback");

                    b.Property<decimal?>("Grade")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnName("grade");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<string>("SubmissionContent")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("submission_content");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("submitted_at");

                    b.HasKey("SubmissionId")
                        .HasName("PK__Submissi__9B5355954A9C148E");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("StudentId");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("Sep490_Eduseen_BE.Models.SubmissionFile", b =>
                {
                    b.Property<int>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("file_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FileId"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("file_url");

                    b.Property<int>("SubmissionId")
                        .HasColumnType("int")
                        .HasColumnName("submission_id");

                    b.HasKey("FileId")
                        .HasName("PK__Submissi__07D884C6EDC7756F");

                    b.HasIndex("SubmissionId");

                    b.ToTable("SubmissionFiles");
                });

            modelBuilder.Entity("Sep490_Eduseen_BE.Models.Transcript", b =>
                {
                    b.Property<int>("TranscriptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("transcript_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TranscriptId"));

                    b.Property<int>("CallId")
                        .HasColumnType("int")
                        .HasColumnName("call_id");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("RecordingUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("recording_url");

                    b.HasKey("TranscriptId")
                        .HasName("PK__Transcri__3D043C3827EBCA35");

                    b.HasIndex("CallId");

                    b.ToTable("Transcripts");
                });

            modelBuilder.Entity("Sep490_Eduseen_BE.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("first_name");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(255)
                        .HasColumnType("nchar(255)")
                        .HasColumnName("refresh_token")
                        .IsFixedLength();

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("refresh_token_expires_at");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("PK__Users__B9BE370F92FB6987");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__AB6E6164AB032028")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "UQ__Users__F3DBC572DCAFB38F")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Sep490_Eduseen_BE.Models.UserLectureProgress", b =>
                {
                    b.Property<int>("ProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("progress_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgressId"));

                    b.Property<bool?>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_completed");

                    b.Property<DateTime?>("LastAccessed")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_accessed");

                    b.Property<int>("LectureId")
                        .HasColumnType("int")
                        .HasColumnName("lecture_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("ProgressId")
                        .HasName("PK__UserLect__49B3D8C1021561E7");

                    b.HasIndex("LectureId");

                    b.HasIndex("UserId");

                    b.ToTable("UserLectureProgress", (string)null);
                });

            modelBuilder.Entity("Sep490_Eduseen_BE.Models.VideoCall", b =>
                {
                    b.Property<int>("CallId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("call_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CallId"));

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_time");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int")
                        .HasColumnName("schedule_id");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.HasKey("CallId")
                        .HasName("PK__VideoCal__427DCE6823EB81AC");

                    b.HasIndex("ScheduleId");

                    b.ToTable("VideoCalls");
                });

            modelBuilder.Entity("Sep490_Eduseen_BE.Models.Assignment", b =>
                {
                    b.HasOne("Sep490_Eduseen_BE.Models.Course", "Course")
                        .WithMany("Assignments")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK__Assignmen__cours__628FA481");

                    b.HasOne("Sep490_Eduseen_BE.Models.User", "CreatedByNavigation")
                        .WithMany("Assignments")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK__Assignmen__creat__6383C8BA");

                    b.Navigation("Course");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("Sep490_Eduseen_BE.Models.ChatMessage", b =>
                {
                    b.HasOne("Sep490_Eduseen_BE.Models.Course", "Course")
                        .WithMany("ChatMessages")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK__ChatMessa__cours__160F4887");

                    b.HasOne("Sep490_Eduseen_BE.Models.User", "Sender")
                        .WithMany("ChatMessages")
                        .HasForeignKey("SenderId")
                        .IsRequired()
                        .HasConstraintName("FK__ChatMessa__sende__17036CC0");

                    b.Navigation("Course");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Sep490_Eduseen_BE.Models.Class", b =>
                {
                    b.HasOne("Sep490_Eduseen_BE.Models.User", "Teacher")
                        .WithMany("Classes")
                        .HasForeignKey("TeacherId")
                        .IsRequired()
                        .HasConstraintName("FK__Classes__teacher__68487DD7");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Sep490_Eduseen_BE.Models.ClassCourse", b =>
                {
                    b.HasOne("Sep490_Eduseen_BE.Models.Class", "Class")
                        .WithMany("ClassCourses")
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("FK__ClassCour__class__6C190EBB");

                    b.HasOne("Sep490_Eduseen_BE.Models.Course", "Course")
                        .WithMany("ClassCourses")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK__ClassCour__cours__6D0D32F4");

                    b.Navigation("Class");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Sep490_Eduseen_BE.Models.ClassStudent", b =>
                {
                    b.HasOne("Sep490_Eduseen_BE.Models.Class", "Class")
                        .WithMany("ClassStudents")
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("FK__ClassStud__class__71D1E811");

                    b.HasOne("Sep490_Eduseen_BE.Models.User", "Student")
                        .WithMany("ClassStudents")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__ClassStud__stude__72C60C4A");

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Sep490_Eduseen_BE.Models.Course", b =>
                {
                    b.HasOne("Sep490_Eduseen_BE.Models.Category", "Category")
                        .WithMany("Courses")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK__Courses__categor__49C3F6B7");

                    b.HasOne("Sep490_Eduseen_BE.Models.User", "Teacher")
                        .WithMany("Courses")
                        .HasForeignKey("TeacherId")
                        .IsRequired()
                        .HasConstraintName("FK__Courses__teacher__4AB81AF0");

                    b.Navigation("Category");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Sep490_Eduseen_BE.Models.EmailConfirmationToken", b =>
                {
                    b.HasOne("Sep490_Eduseen_BE.Models.User", "User")
                        .WithMany("EmailConfirmationTokens")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_EmailConfirmationToken_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sep490_Eduseen_BE.Models.Enrollment", b =>
                {
                    b.HasOne("Sep490_Eduseen_BE.Models.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK__Enrollmen__cours__5535A963");

                    b.HasOne("Sep490_Eduseen_BE.Models.User", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__Enrollmen__stude__5441852A");

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Sep490_Eduseen_BE.Models.Favorite", b =>
                {
                    b.HasOne("Sep490_Eduseen_BE.Models.Course", "Course")
                        .WithMany("Favorites")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK__Favorites__cours__5EBF139D");

                    b.HasOne("Sep490_Eduseen_BE.Models.User", "Student")
                        .WithMany("Favorites")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__Favorites__stude__5DCAEF64");

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Sep490_Eduseen_BE.Models.Lecture", b =>
                {
                    b.HasOne("Sep490_Eduseen_BE.Models.Section", "Section")
                        .WithMany("Lectures")
                        .HasForeignKey("SectionId")
                        .IsRequired()
                        .HasConstraintName("FK__Lectures__sectio__5070F446");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("Sep490_Eduseen_BE.Models.Notification", b =>
                {
                    b.HasOne("Sep490_Eduseen_BE.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Notificat__user___07C12930");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sep490_Eduseen_BE.Models.Otp", b =>
                {
                    b.HasOne("Sep490_Eduseen_BE.Models.User", "User")
                        .WithMany("Otps")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Otps__user_id__43D61337");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sep490_Eduseen_BE.Models.PasswordResetToken", b =>
                {
                    b.HasOne("Sep490_Eduseen_BE.Models.User", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__PasswordR__user___4222D4EF");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sep490_Eduseen_BE.Models.Review", b =>
                {
                    b.HasOne("Sep490_Eduseen_BE.Models.Course", "Course")
                        .WithMany("Reviews")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK__Reviews__course___7D439ABD");

                    b.HasOne("Sep490_Eduseen_BE.Models.User", "Student")
                        .WithMany("Reviews")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__Reviews__student__7E37BEF6");

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Sep490_Eduseen_BE.Models.ReviewResponse", b =>
                {
                    b.HasOne("Sep490_Eduseen_BE.Models.Review", "Review")
                        .WithMany("ReviewResponses")
                        .HasForeignKey("ReviewId")
                        .IsRequired()
                        .HasConstraintName("FK__ReviewRes__revie__02084FDA");

                    b.HasOne("Sep490_Eduseen_BE.Models.User", "Teacher")
                        .WithMany("ReviewResponses")
                        .HasForeignKey("TeacherId")
                        .IsRequired()
                        .HasConstraintName("FK__ReviewRes__teach__02FC7413");

                    b.Navigation("Review");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Sep490_Eduseen_BE.Models.Schedule", b =>
                {
                    b.HasOne("Sep490_Eduseen_BE.Models.User", "Student")
                        .WithMany("ScheduleStudents")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__Schedules__stude__0A9D95DB");

                    b.HasOne("Sep490_Eduseen_BE.Models.User", "Teacher")
                        .WithMany("ScheduleTeachers")
                        .HasForeignKey("TeacherId")
                        .IsRequired()
                        .HasConstraintName("FK__Schedules__teach__0B91BA14");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Sep490_Eduseen_BE.Models.Section", b =>
                {
                    b.HasOne("Sep490_Eduseen_BE.Models.Course", "Course")
                        .WithMany("Sections")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK__Sections__course__4D94879B");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Sep490_Eduseen_BE.Models.Submission", b =>
                {
                    b.HasOne("Sep490_Eduseen_BE.Models.Assignment", "Assignment")
                        .WithMany("Submissions")
                        .HasForeignKey("AssignmentId")
                        .IsRequired()
                        .HasConstraintName("FK__Submissio__assig__75A278F5");

                    b.HasOne("Sep490_Eduseen_BE.Models.User", "Student")
                        .WithMany("Submissions")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__Submissio__stude__76969D2E");

                    b.Navigation("Assignment");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Sep490_Eduseen_BE.Models.SubmissionFile", b =>
                {
                    b.HasOne("Sep490_Eduseen_BE.Models.Submission", "Submission")
                        .WithMany("SubmissionFiles")
                        .HasForeignKey("SubmissionId")
                        .IsRequired()
                        .HasConstraintName("FK__Submissio__submi__797309D9");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("Sep490_Eduseen_BE.Models.Transcript", b =>
                {
                    b.HasOne("Sep490_Eduseen_BE.Models.VideoCall", "Call")
                        .WithMany("Transcripts")
                        .HasForeignKey("CallId")
                        .IsRequired()
                        .HasConstraintName("FK__Transcrip__call___123EB7A3");

                    b.Navigation("Call");
                });

            modelBuilder.Entity("Sep490_Eduseen_BE.Models.User", b =>
                {
                    b.HasOne("Sep490_Eduseen_BE.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK__Users__role_id__3F466844");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Sep490_Eduseen_BE.Models.UserLectureProgress", b =>
                {
                    b.HasOne("Sep490_Eduseen_BE.Models.Lecture", "Lecture")
                        .WithMany("UserLectureProgresses")
                        .HasForeignKey("LectureId")
                        .IsRequired()
                        .HasConstraintName("FK__UserLectu__lectu__59FA5E80");

                    b.HasOne("Sep490_Eduseen_BE.Models.User", "User")
                        .WithMany("UserLectureProgresses")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__UserLectu__user___59063A47");

                    b.Navigation("Lecture");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sep490_Eduseen_BE.Models.VideoCall", b =>
                {
                    b.HasOne("Sep490_Eduseen_BE.Models.Schedule", "Schedule")
                        .WithMany("VideoCalls")
                        .HasForeignKey("ScheduleId")
                        .IsRequired()
                        .HasConstraintName("FK__VideoCall__sched__0E6E26BF");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Sep490_Eduseen_BE.Models.Assignment", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("Sep490_Eduseen_BE.Models.Category", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("Sep490_Eduseen_BE.Models.Class", b =>
                {
                    b.Navigation("ClassCourses");

                    b.Navigation("ClassStudents");
                });

            modelBuilder.Entity("Sep490_Eduseen_BE.Models.Course", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("ChatMessages");

                    b.Navigation("ClassCourses");

                    b.Navigation("Enrollments");

                    b.Navigation("Favorites");

                    b.Navigation("Reviews");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("Sep490_Eduseen_BE.Models.Lecture", b =>
                {
                    b.Navigation("UserLectureProgresses");
                });

            modelBuilder.Entity("Sep490_Eduseen_BE.Models.Review", b =>
                {
                    b.Navigation("ReviewResponses");
                });

            modelBuilder.Entity("Sep490_Eduseen_BE.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Sep490_Eduseen_BE.Models.Schedule", b =>
                {
                    b.Navigation("VideoCalls");
                });

            modelBuilder.Entity("Sep490_Eduseen_BE.Models.Section", b =>
                {
                    b.Navigation("Lectures");
                });

            modelBuilder.Entity("Sep490_Eduseen_BE.Models.Submission", b =>
                {
                    b.Navigation("SubmissionFiles");
                });

            modelBuilder.Entity("Sep490_Eduseen_BE.Models.User", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("ChatMessages");

                    b.Navigation("ClassStudents");

                    b.Navigation("Classes");

                    b.Navigation("Courses");

                    b.Navigation("EmailConfirmationTokens");

                    b.Navigation("Enrollments");

                    b.Navigation("Favorites");

                    b.Navigation("Notifications");

                    b.Navigation("Otps");

                    b.Navigation("PasswordResetTokens");

                    b.Navigation("ReviewResponses");

                    b.Navigation("Reviews");

                    b.Navigation("ScheduleStudents");

                    b.Navigation("ScheduleTeachers");

                    b.Navigation("Submissions");

                    b.Navigation("UserLectureProgresses");
                });

            modelBuilder.Entity("Sep490_Eduseen_BE.Models.VideoCall", b =>
                {
                    b.Navigation("Transcripts");
                });
#pragma warning restore 612, 618
        }
    }
}
